# This file configures suggested labels for the repository
# These will be created automatically by GitHub

- name: "hacktoberfest"
  color: "FF6B35"
  description: "Issues and PRs for Hacktoberfest participants"

- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "bug"
  color: "D73A4A"
  description: "Something isn't working"

- name: "enhancement"
  color: "A2EEEF"
  description: "New feature or request"

- name: "documentation"
  color: "0075CA"
  description: "Improvements or additions to documentation"

- name: "design"
  color: "F9D0C4"
  description: "Design and UI/UX improvements"

- name: "performance"
  color: "FFEF9F"
  description: "Performance improvements"

- name: "accessibility"
  color: "B60205"
  description: "Accessibility improvements"

- name: "testing"
  color: "C5DEF5"
  description: "Testing related improvements"