name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature would benefit the community
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered
      placeholder: Alternatively, we could...

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (small changes)
        - Medium (moderate changes)
        - High (significant changes)
        - Not sure

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to work on this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I'm willing to help with implementation
        - label: I can help with testing

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, mockups, or screenshots about the feature request